import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
    AppBar,
    Toolbar,
    Typography,
    Button,
    Chip,
} from "@mui/material";
import Link from "next/link";
import { AllWords } from "./types/word";
const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <AppBar position="static">
                    <Toolbar>
                        <Typography variant="h6" sx={{ flexGrow: 1 }}>
                            Melons Quiz App
                        </Typography>
                        <Button color="inherit" component={Link} href="/home">
                            Home
                        </Button>
                        <Button color="inherit" component={Link} href="/quiz">
                            Quiz
                        </Button>
                        <Button color="inherit" component={Link} href="/manage">
                            Manage
                        </Button>
                    </Toolbar>
                </AppBar>
                <div>{children}</div>
            </body>
        </html>
    );
}
